import os
import sqlite3
from pathlib import Path

import psycopg
from psycopg.rows import dict_row
from werkzeug.security import generate_password_hash


DATABASE_PATH = Path(__file__).resolve().parent.parent / "iprime_vision.sqlite3"
DATABASE_URL = os.environ.get("DATABASE_URL")


def using_postgres():
    return bool(DATABASE_URL)


def get_connection():
    if using_postgres():
        return psycopg.connect(DATABASE_URL, row_factory=dict_row)
    connection = sqlite3.connect(DATABASE_PATH)
    connection.row_factory = sqlite3.Row
    return connection


def initialize_database():
    if using_postgres():
        with get_connection() as connection:
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    role TEXT NOT NULL DEFAULT 'patient',
                    name TEXT NOT NULL,
                    email TEXT NOT NULL,
                    password TEXT NOT NULL,
                    phone TEXT NOT NULL DEFAULT '',
                    dob TEXT NOT NULL DEFAULT '',
                    address TEXT NOT NULL DEFAULT ''
                )
                """
            )
            connection.execute("CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users (LOWER(email))")
            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS appointments (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    patient_id INTEGER NOT NULL REFERENCES users(id),
                    patient TEXT NOT NULL,
                    date TEXT NOT NULL,
                    time TEXT NOT NULL,
                    service TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'Pending',
                    notes TEXT NOT NULL DEFAULT ''
                )
                """
            )
            connection.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS appointment_date_time_unique ON appointments (date, time)"
            )
            seed_users(connection)
        return

    with get_connection() as connection:
        connection.executescript(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                role TEXT NOT NULL DEFAULT 'patient',
                name TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE COLLATE NOCASE,
                password TEXT NOT NULL,
                phone TEXT NOT NULL DEFAULT '',
                dob TEXT NOT NULL DEFAULT '',
                address TEXT NOT NULL DEFAULT ''
            );

            CREATE TABLE IF NOT EXISTS appointments (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                patient_id INTEGER NOT NULL,
                patient TEXT NOT NULL,
                date TEXT NOT NULL,
                time TEXT NOT NULL,
                service TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'Pending',
                notes TEXT NOT NULL DEFAULT '',
                FOREIGN KEY (patient_id) REFERENCES users(id)
            );

            CREATE UNIQUE INDEX IF NOT EXISTS appointment_date_time_unique
            ON appointments (date, time);
            """
        )
        seed_users(connection)


def seed_users(connection):
    users = [
        (
            "admin",
            os.environ.get("ADMIN_NAME", "Admin User"),
            os.environ.get("ADMIN_EMAIL", "admin@iprimevision.com"),
            generate_password_hash(os.environ.get("ADMIN_PASSWORD", "admin123")),
            os.environ.get("ADMIN_PHONE", "+63 917 000 1111"),
        ),
     
    ]
    if using_postgres():
        with connection.cursor() as cursor:
            cursor.executemany(
                """
                INSERT INTO users (role, name, email, password, phone)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT DO NOTHING
                """,
                users,
            )
    else:
        connection.executemany(
            """
            INSERT OR IGNORE INTO users (role, name, email, password, phone)
            VALUES (?, ?, ?, ?, ?)
            """,
            users,
        )


def placeholder():
    return "%s" if using_postgres() else "?"


def inserted_id(cursor):
    return cursor.fetchone()["id"] if using_postgres() else cursor.lastrowid
